apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o database-analysis-helm
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o database-analysis-helm
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.60
          name: jaeger
          ports:
            - containerPort: 16686
              protocol: TCP
      restartPolicy: Always
