apiVersion: v1
data:
  otel-collector.yaml: |-
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 4317
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
      postgresql:
        endpoint: postgres:5432
        transport: tcp
        username: postgres
        password: example
        databases:
        - postgres
        tls:
            insecure: true

        connection_pool:
          max_idle_time: 10m
          max_lifetime: 0
          max_idle: 2
          max_open: 5

    processors:
    extensions:
      health_check: {}
    exporters:
      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:9090
      logging:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

        metrics:
          receivers: [otlp, postgresql]
          processors: []
          exporters: [prometheus, logging]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: otel-collector
  name: otel-collector-cm0
