apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o database-analysis-helm
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o database-analysis-helm
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: otel-collector
    spec:
      initContainers:
      - name: wait-for-services
        image: opsfleet/depends-on
        args:
        - "-service=postgres"
      containers:
        - args:
            - --config=/etc/otel-collector.yaml
          image: otel/opentelemetry-collector-contrib:0.108.0
          name: otel-collector
          volumeMounts:
            - mountPath: /etc/otel-collector.yaml
              name: otel-collector-cm0
              subPath: otel-collector.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: otel-collector.yaml
                path: otel-collector.yaml
            name: otel-collector-cm0
          name: otel-collector-cm0
