apiVersion: v1
data:
  prometheus.yaml: |-
    scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 5s
        static_configs:
          - targets: ['otel-collector:9090']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
